name: Build & Test Docker Image

on:
  push:
    branches:
      - main
      - devops-docker
  pull_request:


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Run Pytest
        run: pytest tests/
        env:
          PYTHONPATH: .

jobs:
  docker-build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image (with Cache)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: energy_prediction-streamlit-app:latest
          #cache-from: type=gha
          #cache-to: type=gha,mod=max
          load: true

      - name: Start Docker Compose (detached)
        run: docker compose up -d

      - name: Warte kurz, bis die App läuft
        run: sleep 10

      - name: Teste, ob Streamlit läuft
        run: curl --fail http://localhost:8501 || (echo "Streamlit not responding!" && exit 1)
