name: Build Docker Image

on:
  push:
    branches:
      - main
      - devops-docker
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose Build
        run: docker compose build

      - name: Start Docker Compose (detached)
        run: docker compose up -d

      - name: Warte kurz, bis die App läuft
        run: sleep 10

      - name: Teste, ob Streamlit läuft
        run: curl --fail http://localhost:8501 || (echo "Streamlit not responding!" && exit 1)
